#!/bin/bash
cd test
tests=($(ls))
cd ..
for test_case in ${tests[@]}; do
    echo
    echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
    echo "test/$test_case"
    ./parser "test/$test_case"
    echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
done
